import { useMemo } from 'react'
import type { Layout, Rack } from '../../types'

interface PrintCartoucheProps {
  layout: Layout
  rack: Rack
  scaleLabel: string
  generatedAt: Date
}

export default function PrintCartouche({
  layout,
  rack,
  scaleLabel,
  generatedAt,
}: PrintCartoucheProps) {
  const generatedAtLabel = useMemo(
    () => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(generatedAt),
    [generatedAt],
  )

  const rackSpecLabel = `${rack.rack_units}U | ${rack.width} | ${rack.depth_mm}mm`

  const fields: Array<{ label: string; value: string }> = [
    { label: 'Title', value: 'Rack Layout Drawing' },
    { label: 'Layout', value: layout.name },
    { label: 'Rack', value: rack.name },
    { label: 'Rack Spec', value: rackSpecLabel },
    { label: 'Views', value: 'Front + Rear' },
    { label: 'Sheet', value: 'A3 Landscape' },
    { label: 'Scale', value: scaleLabel },
    { label: 'Generated', value: generatedAtLabel },
    { label: 'Generated By', value: 'rack-builder' },
    { label: 'Page', value: '1 / 1' },
  ]

  return (
    <section className="print-cartouche" aria-label="Drawing cartouche">
      {fields.map((field) => (
        <div key={field.label} className="print-cartouche-cell">
          <p className="print-cartouche-label">{field.label}</p>
          <p className="print-cartouche-value" title={field.value}>{field.value}</p>
        </div>
      ))}
    </section>
  )
}
